[programs.localnet]
solana_escrow = "mPDsnHtotv9hio1izTtLS5ejPokcRvXGdyYLoWDPezx"
#solana_escrow_ubuntu = "mPDsnHtotv9hio1izTtLS5ejPokcRvXGdyYLoWDPezx"
#solana_escrow_mac = "8YXzCCFJc4taMWijTpuT2W87KpWp2AkJy4Fsg9Mpnr4q"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/mike/.config/solana/id.json"
#wallet_ubuntu = "/home/mike/.config/solana/id.json"
#wallet_mac = "/Users/michaelcurd/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
