[programs.localnet]
solana_escrow = "GXwRXoHCS1LPZMka3rB4jPgtU9wXVmSnJWumG7DxdiyF"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/mike/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
